[project]
name = "aoc2015"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pylint==3.3.9",
    "pytest==8.3.5",
]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "multiple-statements",
]
